version: "3.7"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=microservices
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /data/mongodb/data/db:/data/db
  application:
    image: ms-dev
    restart: on-failure
    container_name: ms-dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    depends_on:
      - mongodb
