version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: haewon
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data/mongodb/data/db:/data/db
  application:
    container_name: ms
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    depends_on:
      - mongodb
