apiVersion: skaffold/v2beta16
kind: Config
profiles:
- name: build
  build:
    tagPolicy:
      envTemplate:
        template: '{{.MICROSERVICES_IMG_TAG_BUILD}}'
    artifacts:
      - image: gcr.io/columbus-160105/userdatahub/microservices-api-webapp
        context: .
        docker:
          dockerfile: Dockerfile
    local:
      useDockerCLI: true
      useBuildkit: true
- name: dev-deploy
  deploy:
    helm:
      releases:
      - name: columbus-mgmt-helm
        chartPath: ./deploy/microservices-mgmt-helm
        valuesFiles:
        - ./deploy/microservices-mgmt-helm/values-dev.yaml
        setValueTemplates:
          istio.VirtualService.mirror.subset: '{{.MICROSERVICES_IMG_TAG_MIRROR}}'
          tag: '{{.MICROSERVICES_IMG_TAG_DEPLOY}}'
      flags:
        global:
        - --kube-context
        - gke_nm-prod-global-userdata-hub_us-central1-a_userdata-hub-istio-1-11-dev