apiVersion: skaffold/v2beta16
kind: Config
profiles:
- name: build
  build:
    tagPolicy:
      envTemplate:
        template: '{{.MGMT_IMG_TAG_BUILD}}'
    artifacts:
      - image: gcr.io/columbus-160105/userdatahub/columbus-mgmt-api-webapp
        context: .
        docker:
          dockerfile: Dockerfile
    local:
      useDockerCLI: true
      useBuildkit: true
- name: dev-deploy
  deploy:
    helm:
      releases:
      - name: columbus-mgmt-helm
        chartPath: ./deploy/columbus-mgmt-helm
        valuesFiles:
        - ./deploy/columbus-mgmt-helm/values-dev.yaml
        setValueTemplates:
          istio.VirtualService.mirror.subset: '{{.MGMT_IMG_TAG_MIRROR}}'
          istio.temp.VirtualService: '{{.MGMT_ISTIO_TEMP_VIRTUAL_SERVICE}}'
          istio.temp.allowPolicy: '{{.MGMT_ISTIO_TEMP_POLICY}}'
          tag: '{{.MGMT_IMG_TAG_DEPLOY}}'
      flags:
        global:
        - --kube-context
        - gke_nm-prod-global-userdata-hub_us-central1-a_userdata-hub-istio-1-11-dev
- name: qa-deploy
  deploy:
    helm:
      releases:
      - name: columbus-mgmt-helm
        chartPath: ./deploy/columbus-mgmt-helm
        valuesFiles:
        - ./deploy/columbus-mgmt-helm/values-qa.yaml
        setValueTemplates:
          istio.VirtualService.mirror.subset: '{{.MGMT_IMG_TAG_MIRROR}}'
          istio.temp.VirtualService: '{{.MGMT_ISTIO_TEMP_VIRTUAL_SERVICE}}'
          istio.temp.allowPolicy: '{{.MGMT_ISTIO_TEMP_POLICY}}'
          tag: '{{.MGMT_IMG_TAG_DEPLOY}}'
      flags:
        global:
        - --kube-context
        - gke_nm-prod-global-userdata-hub_us-central1-a_userdata-hub-istio-1-11-qa
- name: test-deploy
  deploy:
    helm:
      releases:
      - name: columbus-mgmt-helm
        chartPath: ./deploy/columbus-mgmt-helm
        valuesFiles:
        - ./deploy/columbus-mgmt-helm/values-test.yaml
        setValueTemplates:
          istio.VirtualService.mirror.subset: '{{.MGMT_IMG_TAG_MIRROR}}'
          istio.temp.VirtualService: '{{.MGMT_ISTIO_TEMP_VIRTUAL_SERVICE}}'
          istio.temp.allowPolicy: '{{.MGMT_ISTIO_TEMP_POLICY}}'
          tag: '{{.MGMT_IMG_TAG_DEPLOY}}'
      flags:
        global:
        - --kube-context
        - gke_nm-prod-global-userdata-hub_us-central1_userdata-hub-istio-1-11-test
- name: prod-deploy
  deploy:
    helm:
      releases:
      - name: columbus-mgmt-helm
        chartPath: ./deploy/columbus-mgmt-helm
        valuesFiles:
        - ./deploy/columbus-mgmt-helm/values-prod.yaml
        setValueTemplates:
          istio.VirtualService.mirror.subset: '{{.MGMT_IMG_TAG_MIRROR}}'
          istio.temp.VirtualService: '{{.MGMT_ISTIO_TEMP_VIRTUAL_SERVICE}}'
          istio.temp.allowPolicy: '{{.MGMT_ISTIO_TEMP_POLICY}}'
          tag: '{{.MGMT_IMG_TAG_DEPLOY}}'
      flags:
        global:
        - --kube-context
        - gke_nm-prod-global-userdata-hub_us-central1-a_userdata-hub-istio-1-11
