columbus:
  bigquery:
    partition-dataset: userdata_hub_partition_segments_test
  profile:
    api-key: AIzaSyB_JXP4EkOqn08OBQ9gZgDDlyNCuI65zRQ
feign:
  columbus-mgmt-api:
    url: http://localhost:9101
  columbus-trigger-api:
    url: http://localhost:9202
  columbus-data-api:
    url: http://localhost:9301
  nais-api:
    url: https://nais-api-public.nmn.io
  gmeta-api:
    url: http://gmeta.netmarble.com
logging:
  pretty-print: true
management:
  server:
    port: 9999
gcp:
  config:
    bigquery:
      dataset: user_labels_test
okta:
  oauth2:
    client-id: ENC(X+HeZXdEDdxFx2nUikN8CHwEPO2tF30QHV08/3Canvg=)
    client-secret: ENC(tzSTtu9QNlZDTvKKxSgI6fex30ia7dr0/m+78Uf6wZo8XnJpIUJYrViB2IzTndHLEzrgzSv+o5g=)
    issuer: https://sso.nmn.io
    logout-uri: http://localhost:9203/dashboard
spring:
  application:
    name: dashboard-docker-local
  config:
    import : "zookeeper:localhost:2181"
    activate:
      on-profile: docker-local
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 86400