apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Values.service.name }}-vs
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
    - {{ $.Values.istio.VirtualService.host }}
  http:
    - match:
        - uri:
            prefix: /mgmt/
      route:
        {{- range splitList "#" $.Values.tag }}
        {{- $tag := (split "%" . )._0 | replace "." "-" }}
        {{- $weight := (split "%" . )._1 }}
        - destination:
            port:
              number: {{ $.Values.service.internalPort }}
            host: {{ $.Values.istio.VirtualService.host }}
            subset: tag-{{ $tag }}
          weight: {{ $weight }}
        {{- end }}
{{/*      timeout: {{ $.Values.istio.VirtualService.timeout}}*/}}
      {{- if and $.Values.istio.VirtualService.mirror.subset (ne $.Values.istio.VirtualService.mirror.subset "<no value>" ) }}
      mirror:
        host: {{ $.Values.istio.VirtualService.host }}
        subset: tag-{{ $.Values.istio.VirtualService.mirror.subset }}
        port:
          number: {{ $.Values.service.internalPort }}
      mirror_percent: {{ $.Values.istio.VirtualService.mirror.percent }}
      {{- end }}
    - match:
        - uri:
            prefix: /mgmt/v2
      route:
        {{- range splitList "#" $.Values.tag }}
        {{- $tag := (split "%" . )._0 | replace "." "-" }}
        {{- $weight := (split "%" . )._1 }}
        - destination:
            port:
              number: {{ $.Values.service.internalPort }}
            host: {{ $.Values.istio.VirtualService.host }}
            subset: tag-{{ $tag }}
          weight: {{ $weight }}
        {{- end }}
{{/*      timeout: {{ $.Values.istio.VirtualService.timeout}}*/}}
      {{- if and $.Values.istio.VirtualService.mirror.subset (ne $.Values.istio.VirtualService.mirror.subset "<no value>" ) }}
      mirror:
        host: {{ $.Values.istio.VirtualService.host }}
        subset: tag-{{ $.Values.istio.VirtualService.mirror.subset }}
        port:
          number: {{ $.Values.service.internalPort }}
      mirror_percent: {{ $.Values.istio.VirtualService.mirror.percent }}
      {{- end }}