apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .Values.service.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: http-{{ .Values.service.name }}-{{ .Values.service.internalPort }}
      protocol: TCP
    - port: {{ .Values.service.actuatorPort }}
      targetPort: {{ .Values.service.actuatorPort }}
      protocol: TCP
      name: http-{{ .Values.service.name }}-{{ .Values.service.actuatorPort }}
  type: {{ .Values.service.type }}
