profile: prod
namespace: default
image: gcr.io/columbus-160105/userdatahub/columbus-mgmt-api-webapp
tag: latest%100
replicaCnt: 2
monitoring:
  name: otel-agent
  image: gcr.io/columbus-160105/monitoring/opentelemetry-collector-contrib
  tag: 0.34.0
  port:
    zPages: 55679
    zipkin: 9411
    exporter: 55678
    health: 13133
  resources:
    request:
      cpu: 100m
      memory: 300Mi
    limit:
      cpu: 200m
      memory: 600Mi
service:
  name: microservices
  credentials: mgmt-gcp-key
  type: ClusterIP
  externalPort: 9101
  internalPort: 9101
  actuatorPort: 9999
  internalPortName: mgmt
  livenessPath: /health
  readinessPath: /health
  prometheusPath: /actuator/prometheus
liveness:
  initialDelaySeconds: 50
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readiness:
  initialDelaySeconds: 50
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
resources:
  request:
    cpu: 500m
    memory: 1Gi
  limit:
    cpu: 2000m
    memory: 2Gi
istio:
  proxy:
    resources:
      request:
        cpu: 100m
        memory: 128Mi
      limit:
        cpu: 2000m
        memory: 2500Mi
  DestinationRule:
    host: mgmt
  VirtualService:
    host: mgmt.default.svc.cluster.local
    domain: clbs.nmn.io
    timeout: 3s
    mirror:
      subset: latest
      percent: 100
    principals:
      - cluster.local/ns/default/sa/mgmt
      - cluster.local/ns/service/sa/trigger
      - cluster.local/ns/service/sa/scaler
      - cluster.local/ns/service/sa/admin
      - cluster.local/ns/service/sa/dashboard
      - cluster.local/ns/data/sa/columbus-data-api
      - cluster.local/ns/data/sa/usr-profile
  temp:
    allowPolicy: true
    VirtualService: true
