profile: dev
namespace: service
image: gcr.io/columbus-160105/userdatahub/columbus-ms-api-webapp
tag: latest%100
replicaCnt: 1
monitoring:
  name: otel-agent
  image: gcr.io/columbus-160105/monitoring/opentelemetry-collector-contrib
  tag: 0.34.0
  port:
    zPages: 55679
    zipkin: 9411
    exporter: 55678
    health: 13133
  resources:
    request:
      cpu: 100m
      memory: 300Mi
    limit:
      cpu: 200m
      memory: 600Mi
service:
  name: ms-dev
  credentials: mgmt-gcp-key
  type: ClusterIP
  externalPort: 8989
  internalPort: 8989
  actuatorPort: 9999
  internalPortName: ms
  livenessPath: /health
  readinessPath: /health
  prometheusPath: /actuator/prometheus
liveness:
  initialDelaySeconds: 50
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readiness:
  initialDelaySeconds: 50
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
resources:
  request:
    cpu: 200m
    memory: 1Gi
  limit:
    cpu: 1000m
    memory: 2Gi
istio:
  proxy:
    resources:
      request:
        cpu: 100m
        memory: 128Mi
      limit:
        cpu: 1000m
        memory: 2500Mi
  DestinationRule:
    host: ms-dev
  VirtualService:
    host: ms-dev.default.svc.cluster.local
    domain: dev-clbs.nmn.io
    timeout: 3s
    mirror:
      subset: latest
      percent: 100
    principals:
      - cluster.local/ns/default/sa/ms-mgmt-dev
      - cluster.local/ns/service/sa/ms-profile-dev
  temp:
    allowPolicy: true
    VirtualService: true